# This is a basic workflow to help you get started with Actions
name: CI_DEV
# Controls when the workflow will run
on:
  # Triggers the workflow oa push or pull request events but only for the "dev" branch
  push:
    branches:
      - dev
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs :
  # This workflow contains a single job called "build"
  migrate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: flyway/flyway
    steps:
      - uses: actions/checkout@v3

      - name: Run flyway migrate
        run: |
            export JAVA_ARGS=--add-opens=java.base/java.nio=ALL-UNNAMED
            flyway -user="${{ secrets.SNOWFLAKE_USER }}" -password=${{ secrets.SNOWFLAKE_PASSWORD }} -configFiles=configs/dev.conf migrate
        shell: bash